[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++20", "-Wall", "-O2"]

[[languages.cpp.environments]]
CXX = "clang++"
CXXFLAGS = [
    "-std=c++17",
    "-Wall",
    "-g",
    "-fsanitize=undefined",
    "-D_GLIBCXX_DEBUG",
]
